[tool.poetry]
name = "pycvesearch"
version = "1.0"
description = "Python API for CVE search."
authors = ["RaphaÃ«l Vinot <raphael.vinot@circl.lu>"]
license = "Apache-2.0"
repository = "https://github.com/cve-search/PyCVESearch"
readme = "README.md"

classifiers=[
    'License :: OSI Approved :: Apache Software License',
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Programming Language :: Python :: 3',
    'Topic :: Security',
    'Topic :: Internet',
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
nose = "^1.3.7"
coveralls = "^2.0.0"
codecov = "^2.0.22"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
